//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetHopital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int IdAdmission { get; set; }
        public bool ChirurgieProgramme { get; set; }
        public System.DateTime DateAdmission { get; set; }
        public Nullable<System.DateTime> DateChirurgie { get; set; }
        public Nullable<System.DateTime> DateConge { get; set; }
        public Nullable<bool> LocationTeleviseur { get; set; }
        public Nullable<bool> LocationTelephone { get; set; }
        public string NumAssuranceMaladie { get; set; }
        public int idLit { get; set; }
        public string idMedecin { get; set; }
        public Nullable<bool> ChambrePriveGratuit { get; set; }
    
        public virtual Lit Lit { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
